# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2019
# Marc Ferland, Amotus Solutions Inc.

obj-$(CONFIG_TARGET_VARISCITE_DART6UL_EVK) += eeprom.o
obj-$(CONFIG_TARGET_VARISCITE_DART6UL_IDE) += eeprom.o
