# SPDX-License-Identifier: GPL-2.0+
#
# DIGI Connected Board ccardimx28js Support
# Copyright (C) 2020 Amotus Solutions
# Author: Walter Bonetti <bonettiw@amotus.ca>

ifndef	CONFIG_SPL_BUILD
obj-y	:= ccardimx28js.o
else
obj-y	:= iomux.o
endif
